### ISSUE TITLE
Zero registration fails in HttpClient

### ISSUE THREAD

**Issue by anti43** [ZeroPush/ZeroPush-java#3]
Code:

```java
ZeroPush.registration().register(token).execute();
```

Exception:

```java
06-16 11:49:22.050 E/ZeroPush﹕ Item may not be null
java.lang.IllegalArgumentException: Item may not be null
at org.apache.http.util.Args.notNull(Args.java:48)
at org.apache.http.config.RegistryBuilder.register(RegistryBuilder.java:58)
at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:727)
at com.zeropush.request.ZeroPushRequestExecutor.getHttpClient(ZeroPushRequestExecutor.java:69)
at com.zeropush.request.ZeroPushRequestExecutor.execute(ZeroPushRequestExecutor.java:47)
at com.zeropush.register.Register.execute(Register.java:92)
at lu.eevol.commons.ZeroPushBroadcastReceiver$1.doInBackground(ZeroPushBroadcastReceiver.java:78)
at lu.eevol.commons.ZeroPushBroadcastReceiver$1.doInBackground(ZeroPushBroadcastReceiver.java:66)
at lu.eevol.commons.AsyncTask$2.call(AsyncTask.java:314)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at lu.eevol.commons.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:864)
```

my hhtp client in the project is

```
compile 'org.apache.httpcomponents:httpclient-android:4.3.5'
```

**Comment by smiklosovic** [comment]
Hi,

I am not completely sure what is the cause of the problem. This is not the fault of the ZeroPush library as such. ZeroPush Android artifact uses this HTTP client artifact and it is of version 4.3.5.1 (1). Would it be possible to delete your compile dependency and use what is already "bundled" in ZeroPush Android dependency?

Please let me know what it is going.

https://github.com/ZeroPush/ZeroPush-java/blob/master/impl-android/pom.xml#L58-L61

Stefan

**Comment by anti43** [comment]
Hi!

I can confirm that switching to 4.3.5.1 fixes the issue!

Best,

Andreas
